# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: zeinmiftah@gmail.com
copyright_name: Your/Project/Corporate Name
description: "Engineer | Mercenary | Web Developer | Linux User | Scatterbrain #SavePalestine #SaveSyria #SaveIndonesia"
baseurl: "/clean-blog-jekyll"
url: "http://zmiftah.github.io"
twitter_username: miftahzein
github_username:  zmiftah
facebook_username:  zeinmiftah
email_username:  zeinmiftah@gmail.com

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
# To enable populate shortname and unhash the line below.
disqus: zeinmiftah

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]